config/routes.rb
Rails.application.routes.draw do
  resources :favorites, only: [:create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :users,    only: [:new, :create, :show]
  root "feeds#index"
  resources :feeds do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :feed
end

app/models/feed.rb
class Feed < ApplicationRecord
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  belongs_to :user
  validates :image, presence: true
  validates :title, presence: true
  validates :content, presence: true
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  has_many :favorites, dependent: :destroy
  has_many :feeds
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  validates :name,     presence: true, length: { maximum: 30 }
  validates :email,    presence: true, length: { maximum: 255},
                         format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  def authenticate_user
    if @current_user == nil
      flash[:notice] = t('notice.login_needed')
      redirect_to new_session_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(feed_id: params[:feed_id])
    redirect_to feeds_url, notice: "#{favorite.feed.user.name}さんのブログをお気に入り登録しました"
  end
  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to feeds_url, notice: "#{favorite.feed.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]

  # GET /feeds
  # GET /feeds.json
  def index
    @feeds = Feed.all
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
    @favorite = current_user.favorites.find_by(feed_id: @feed.id)
  end

  # GET /feeds/new
  def new
    if params[:back]
      @feed = Feed.new(feed_params)
    else
      @feed = Feed.new
    end
  end

  # GET /feeds/1/edit
  def edit
  end

  # POST /feeds
  # POST /feeds.json
  def create
    @feed = Feed.new(feed_params)
    @feed.user_id = current_user.id

    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
        format.json { render :show, status: :created, location: @feed }
      else
        format.html { render :new }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feeds/1
  # PATCH/PUT /feeds/1.json
  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: 'Feed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def confirm
    @feed = Feed.new(feed_params)
    @feed.user_id = current_user.id
    render :new if @feed.invalid?
  end
end

private
# Use callbacks to share common setup or constraints between actions.
def set_feed
  @feed = Feed.find(params[:id])
end

# Only allow a list of trusted parameters through.
def feed_params
  params.require(:feed).permit(:image, :image_cache, :title, :content, :user_id)
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      #renderでなく、redirect_toだとどのような動きになるか試したい => アクションを起こさない（HTTPリクエストなし）
      render :new
    end
  end
  def show
    #パラメータが飛ぶところ、params[:id]をもとに、そのidに紐づくデータをデータベースから取得
    @user = User.find(params[:id])
  end
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_feeds_path
    elsif action_name == 'edit'
      feed_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/feeds/_form.html.erb
<% if logged_in? %>
  <%= form_with(model: feed, local: true, url:choose_new_or_edit) do |form| %>
    <% if feed.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

        <ul>
        <% feed.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :image %>
      <%= image_tag(@feed.image.url) if @feed.image && @feed.image.url %>
      <%= form.file_field :image %>
      <%= form.hidden_field :image_cache %>
      <%= form.label :タイトル %>
      <%= form.text_field :title %>
      <%= form.label :内容 %>
      <%= form.text_field :content %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
  <% else %>
    <h3>ログインしないと、画像やコメントの投稿・編集はできません</h3>
<% end %>

app/views/feeds/confirm.html.erb
<h2>確認画面</h2>
<%= form_with(model: @feed, url: feeds_path, local: true) do |form| %>
  <h4>[タイトル]</h4>
  <h4><%= @feed.title %></h4>
  <h4>[内容]</h4>
  <h4><%= @feed.content %></h4>
  <%= image_tag(@feed.image.url) if @feed.image && @feed.image.url %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.submit "投稿する" %>
<% end %>
<%= form_with(model:@feed, url:feeds_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.submit "戻る", name: "back" %>
<% end %>

app/views/feeds/edit.html.erb
<h1>編集画面</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<p id="notice"><%= notice %></p>

<h2>投稿一覧</h2>

<table>
  <thead>
    <tr>
      <th>投稿者</th>
      <th>画像</th>
      <th>タイトル</th>
      <th>内容</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feeds.each do |feed| %>
      <tr>
        <td><%= feed.user.name %></td>
        <td><%= image_tag feed.image.url %></td>
        <td><%= feed.title %></td>
        <td><%= feed.content %></td>
        <td><%= link_to 'Show', feed %></td>
        <% if logged_in? %>
          <td><%= link_to 'Edit', edit_feed_path(feed) %></td>
          <td><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if logged_in? %>
  <p><%= link_to '新規投稿へ', new_feed_path %></P>
<% end %>

app/views/feeds/new.html.erb
<h1>新規の投稿</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<h4>[タイトル]</h4>
<h4><%= @feed.title %></h4>
<h4>[内容]</h4>
<h4><%= @feed.content %></h4>
<p>
  <strong>Image:</strong>
  <%= image_tag @feed.image.url %>
</p>
<% if logged_in? %>
  <%= link_to 'Edit', edit_feed_path(@feed) %>
<% end %>
<%= link_to 'Back', feeds_path %>

<% unless @feed.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(feed_id: @feed.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FacebookClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <% if logged_in? %>
      <header>
        <a>画像やコメントを投稿しよう</a>
        <%= link_to '[一覧へ]', feeds_path %>
        <%= link_to '[新規投稿へ]', new_feed_path %>
      </header>
      <%= link_to "Profile", user_path(current_user.id) %>
      <%= link_to "Logout", session_path(current_user.id), method: :delete %>
      <p class="login"><%= @current_user.name %>さん（<%= @current_user.email %>）は、現在ログイン中です<p>
    <% else %>
    <header>
      <a>ログインして、画像やコメントを投稿しよう</a>
      <%= link_to '[一覧へ]', feeds_path %>
    </header>
      <p class="login">現在ログインしていません</p>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %>
    <% end %>
    <%= yield %>
  </body
  <footer>
    <p>Toukou課題株式会社(架空)</p>
  </footer>
</html>

app/views/users/new.html.erb
<h1>Sign up</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h4>以下の名前とメールアドレスで登録しています</h4>
<p><%= @user.name %></p>
<p>メールアドレス：<%= @user.email %></p>

<% if logged_in? %>
  <p><%= link_to '一覧へ', feeds_path %></p>
  <p><%= link_to '新規投稿へ', new_feed_path %></p>
<% end %>